AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: "Practice SAM"

Globals:
  Function:
    Runtime: nodejs12.x
    Timeout: 60
    Tracing: Active # X-Ray tracing mode. Accepted values are Active and PassThrough
    Tags:
      Application: serverless-web-app-practice
  Api:
    Auth:
      UsagePlan: # optional
        UsagePlanName: DailyUsagePlan
        CreateUsagePlan: PER_API
        Description: Limit 5000 executions per day, throttle 10%
        Quota:
          Limit: 5000
          Period: DAY
        Throttle:
          BurstLimit: 100
          RateLimit: 50

Parameters:
  VersionParam:
    Type: String
    Default: v1
  StageNameParam:
    Type: String
    Default: prod
  CognitoDomainName:
    Type: String
    Default: mytodoappdemo

  # For Amplify Console Frontend Hosting
  Repository:
    Type: String
    Description: GitHub Repository URL
  Branch:
    Type: String
    Description: GitHub Branch
    Default: master
  OauthToken:
    Type: String
    Description: GitHub Repository URL
    NoEcho: true

Resources:
  TodoUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      AdminCreateUserConfig:
        AllowAdminCreateUserOnly: false
      UserPoolName: TodoUsers
      UsernameAttributes:
      - email
      AutoVerifiedAttributes:
      - email
      Policies:
        PasswordPolicy:
          MinimumLength: 6
          RequireLowercase: true
          RequireNumbers: false
          RequireSymbols: false
          RequireUppercase: true

  TodoUserPoolTokenClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      UserPoolId: !Ref TodoUserPool
      GenerateSecret: false
      AllowedOAuthFlowsUserPoolClient: true
      AllowedOAuthFlows: ['code', 'implicit']
      CallbackURLs: ['http://localhost:3000', 'http://localhost:8080' ,'https://localhost', !Join ['', ['https://', !GetAtt AmplifyBranch.BranchName, '.', !GetAtt AmplifyApp.DefaultDomain]]]
      SupportedIdentityProviders: ['COGNITO']
      AllowedOAuthScopes: ['phone', 'email', 'openid']
      ExplicitAuthFlows:
      - ALLOW_USER_PASSWORD_AUTH 
      #Flow names without the ALLOW_ prefix are deprecated in favor of new names with the ALLOW_ prefix.

  TodoDomain:
    Type: AWS::Cognito::UserPoolDomain
    #AWS::Cognito::UserPoolDomain resource creates a new domain for a user pool.
    Properties:
      Domain: !Join ['-', [!Ref CognitoDomainName, !Ref AWS::StackName]]
      UserPoolId: !Ref TodoUserPool

  TodoTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Join ['-', [todo-table, !Ref AWS::StackName]]
      KeySchema:
          - AttributeName: cognito-username
            KeyType: HASH
          - AttributeName: id
            KeyType: RANGE
      AttributeDefinitions:
          - AttributeName: cognito-username
            AttributeType: S
          - AttributeName: id
            AttributeType: S
      ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1                  
      SSESpecification: 
      # Represents the settings used to enable server-side encryption.
        SSEEnabled: true

# API declaration
  TodoApi:
    Type: AWS::Serverless::Api
    MethodSettings: 
        DataTraceEnabled: true
        MetricsEnabled: true
        HttpMethod: '*'
        ResourcePath: !Sub '${VersionParam}/*'
        LoggingLevel: INFO
    AccessLogSetting:
      DestinationArn: !Sub 'arn:${AWS::Partition}:logs:${AWS::Region}:${AWS::AccountId}:log-group:${ApiAccessLogGroup}'
      Format: '$context.identity.sourceIp $context.authorizer.claims.sub [$context.requestTime] "$context.httpMethod $context.resourcePath $context.protocol" $context.status $context.requestId $context.awsEndpointRequestId $context.xrayTraceId $context.responseLatency $context.integrationLatency "$context.error.message"'
    Properties:
      Name: TodoApi
      StageName: !Ref StageNameParam
      TracingEnabled: true
      Cors:
        AllowOrigin: "'*'"
        AllowMethods: "'OPTIONS,HEAD,GET,PUT,POST,DELETE'"
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
      Auth:
        Authorizers:
          CognitoAuthorizer:
            UserPoolArn: !GetAtt "TodoUserPool.Arn"

  # Lambda Functions and API gateways
  GetTodoFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: todo-src/getTodo
      Handler: app.getToDoItem
      Tracing: Active
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref TodoTable
        - CloudWatchPutMetricPolicy: {}
      Environment:
        Variables:
          TABLE_NAME: !Ref TodoTable
          AWS_NODEJS_CONNECTION_REUSE_ENABLED: "1"
          USE_DYNAMODB_LOCAL: "0"
          DYNAMODB_LOCAL_URI: ""

      Events: # Specifies the events that trigger this function.
        GetItem:
          Type: Api 
          Properties:
            Path: /item/{id}
            Method: get
            RestApiId: !Ref TodoApi
            Auth:
              Authorizer: CognitoAuthorizer

  GetAllTodoFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: todo-src/getAllTodo
      Handler: app.getAllToDoItem
      Tracing: Active
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref TodoTable
        - CloudWatchPutMetricPolicy: {}
      Environment:
        Variables:
          TABLE_NAME: !Ref TodoTable
          AWS_NODEJS_CONNECTION_REUSE_ENABLED: "1"
          ENDPOINT_OVERRIDE: ""

      Events: # Specifies the events that trigger this function.
        GetItem:
          Type: Api 
          Properties:
            Path: /item
            Method: get
            RestApiId: !Ref TodoApi
            Auth:
              Authorizer: CognitoAuthorizer

  CompleteTodoFunction:
      Type: AWS::Serverless::Function 
      Properties:
        CodeUri: todo-src/completeTodo/
        Handler: app.completeToDoItem
        Tracing: Active
        Policies:
          - DynamoDBCrudPolicy:
              TableName: !Ref TodoTable
          - CloudWatchPutMetricPolicy: {}
        Environment:
          Variables:
            TABLE_NAME: !Ref TodoTable
            AWS_NODEJS_CONNECTION_REUSE_ENABLED: "1"
            ENDPOINT_OVERRIDE: ""

        Events: # Specifies the events that trigger this function.
          CompleteItem:
            Type: Api 
            Properties:
              Path: /item/{id}/done
              Method: post
              RestApiId: !Ref TodoApi
              Auth:
                Authorizer: CognitoAuthorizer

  AddTodoFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: todo-src/addTodo/
      Handler: app.addToDoItem
      Tracing: Active
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref TodoTable
        - CloudWatchPutMetricPolicy: {}
      Environment:
        Variables:
          TABLE_NAME: !Ref TodoTable
          AWS_NODEJS_CONNECTION_REUSE_ENABLED: "1"
          ENDPOINT_OVERRIDE: ""

      Events: # Specifies the events that trigger this function.
        PutItem:
          Type: Api 
          Properties:
            Path: /item
            Method: POST
            RestApiId: !Ref TodoApi
            Auth:
              Authorizer: CognitoAuthorizer

  UpdateTodoFunction:
      Type: AWS::Serverless::Function 
      Properties:
        CodeUri: todo-src/updateTodo/
        Handler: app.updateToDoItem
        Tracing: Active
        Policies:
          - DynamoDBCrudPolicy:
              TableName: !Ref TodoTable
          - CloudWatchPutMetricPolicy: {}
        Environment:
          Variables:
            TABLE_NAME: !Ref TodoTable
            AWS_NODEJS_CONNECTION_REUSE_ENABLED: "1"
        Events: # Specifies the events that trigger this function.
          UpdateItem:
            Type: Api 
            Properties:
              Path: /item/{id}
              Method: PUT
              RestApiId: !Ref TodoApi
              Auth:
                Authorizer: CognitoAuthorizer

  DeleteTodoFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: todo-src/deleteTodo
      Handler: app.deleteToDoItem
      Tracing: Active
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref TodoTable
        - CloudWatchPutMetricPolicy: {}
      Environment:
        Variables:
          TABLE_NAME: !Ref TodoTable
          AWS_NODEJS_CONNECTION_REUSE_ENABLED: "1"
          ENDPOINT_OVERRIDE: ""

      Events: # Specifies the events that trigger this function.
        DeleteItem:
          Type: Api 
          Properties:
            Path: /item/{id}
            Method: DELETE
            RestApiId: !Ref TodoApi
            Auth:
              Authorizer: CognitoAuthorizer


# This role allows API Gateway to push execution and access logs to CloudWatch logs
  ApiGatewayPushToCloudWatchRole:
    Type: AWS::IAM::Role
    Properties:
      Description: "Push logs to CloudWatch logs from API Gateway"
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - "apigateway.amazonaws.com"
            Action: "sts:AssumeRole"
        ManagedPolicyArns:
          - !Sub "arn:${AWS::Partition}:iam::aws:policy/service-role/AmazonAPIGatewayPushToCloudWatchLogs"
# Specifies a log group
  ApiAccessLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/apigateway/AccessLog-${TodoApi}
      RetentionInDays: 365

# Amplify console hosting for static website
  AmplifyRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - amplify.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Policies:
        - PolicyName: Amplify
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: 'amplify:*'
                Resource: '*'
# The AWS::Amplify::App resource creates Apps in the Amplify Console. 
# An App is a collection of branches.
  AmplifyApp:
    Type: AWS::Amplify::App
    Properties:
      Name: TodoApp
      Repository: !Ref Repository
      Description: Todo example app
      OauthToken: !Ref OauthToken
      # if the value ends with whitespace, like a newline, 
      # YAML will preserve it. To strip the character, use the strip operator(-).
      BuildSpec: |-
        version: 0.1
        frontend:
          phases:
            build:
              commands:
                - cd www/src
                - npm install
                - npm run build
          artifacts:
            baseDirectory: www/build/
            files:
              - '**/*'
      Tags:
        - Key: Name
          Value: Todo
      IAMServiceRole: !GetAtt AmplifyRole.Arn

  AmplifyBranch:
    Type: AWS::Amplify::Branch
    Properties:
      BranchName: !Ref Branch
      AppId: !GetAtt AmplifyApp.AppId
      Description: Amplify Console Branch
      EnableAutoBuild: true
      Tags:
        - Key: Name
          Value: todo-amplify-console
        - Key: Branch
          Value: !Ref Branch

  Outputs:
    # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
    # Find out more about other implicit resources you can reference within SAM
    # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
    TodoFunctionApi:
      Description: API Gateway endpoint URL for Prod stage
      Value: !Sub "https://${TodoApi}.execute-api.${AWS::Region}.amazonaws.com/{StageNameParam}"
    CognitoID:
      Description: The Cognito UserPool ID
      Value: !Ref TodoUserPool
    CognitoClientID:
      Description: The Cognito UserPool Client ID
      Value: !Ref TodoUserPoolTokenClient
    CognitoDomainName:
      Description: The Cognito Hosted UI Domain Name
      Value: !Join ['', [!Ref CognitoDomainName, '-', !Ref AWS::StackName, '.auth.', !Ref AWS::Region, '.amazoncognito.com']]
    AmplifyURL:
      Value: !Join ['', ['https://', !GetAtt AmplifyBranch.BranchName, '.', !GetAtt AmplifyApp.DefaultDomain]]
